config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :gists
  root :to => 'gists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gist.rb
class Gist < ActiveRecord::Base
   has_many :gist_files, dependent: :destroy
   accepts_nested_attributes_for :gist_files, :allow_destroy => true
end

app/models/gist_file.rb
class GistFile < ActiveRecord::Base
   belongs_to :gist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  rescue_from ActiveRecord::RecordNotFound, :with => :render_404

  def render_404
    render :template => "errors/error_404", :status => 404
  end

end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_gist, only: [:show, :edit, :update, :destroy]

  def index
    @all_gist = Gist.all
  end

  def show
  end

  def update
    new_records = []
    current_old_records = Hash.new(0)
    gist_params[:gist_files_attributes].keys.each do |key|
      #use strong params and reconstruct object for saving
      gist_file_id = gist_params[:gist_files_attributes][key][:id]
      gist_file_record = {
        id: gist_file_id,
        file_content: gist_params[:gist_files_attributes][key][:file_content],
        extension_type: gist_params[:gist_files_attributes][key][:extension_type],
        gist_id: gist_params[:id]
      }
      #if gist file id empty then it's a new record/otherwise assign to hash
      if gist_file_id.empty?
        new_records << gist_file_record
      else
        current_old_records[gist_file_id] =  gist_file_record
      end
    end
    #convert ids to ints
    current_old_record_ids = current_old_records.keys.map {|id| id.to_i }
    actual_db_records = @gist.gist_files.pluck(:id)
    #compare old ids with updated ids from front end
    records_to_remove = actual_db_records - current_old_record_ids

    #create newly linked gist_files
    GistFile.create(new_records)
    #remove gist_files that have been removed on front end
    @gist.gist_files.delete(*records_to_remove)
    respond_to do |format|
      #update assoc gist files
      if (@gist.update(description: gist_params[:description], gist_files_attributes: current_old_records.values))
        format.html  { redirect_to(@gist,
                      :notice => 'Gist was successfully created.') }
        format.json  { render :json => @gist,
                      :status => :created, :location => @gist }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @gist.errors,
                      :status => :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def new
  end

  def create
    @gist = Gist.new(gist_params)
    respond_to do |format|
      if @gist.save
        format.html  { redirect_to(@gist,
                      :notice => 'Gist was successfully created.') }
        format.json  { render :json => @gist,
                      :status => :created, :location => @gist }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @gist.errors,
                      :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @gist.destroy
     respond_to do |format|
       format.html { redirect_to gists_url, notice: 'Gist was
       successfully destroyed.' }
       format.json { head :no_content }
     end
  end

  private
  def set_gist
    @gist = Gist.find(params[:id])
  end

  def gist_params
    params.require(:gist).permit(:id, :description, :public, :gist_files_attributes => [:id, :file_content, :extension_type])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gists/_bottom_form_content.html.erb
<div style="display:flex;margin-top: 20px;">
  <div class="submit_item" style="margin-right:55%;">
  <button id="add_file">Add file</button>
  </div>
  <div class="submit_item">
    <button class="create_gist" style="
    background-color: #e6e1c0;
    background-image: linear-gradient(#fffad5,#e6e1c0);
    border-color: #e3deb9;
    ">Create secret gist</button>
  </div>
  <div class="submit_item">
    <button class="create_gist">Create public gist</button>
  </div>
</div>

app/views/gists/_form.html.erb
<div data-editor-number="<%=(!idx.nil? ? idx.to_s : "0")%>" class="gist_content_div" style="margin-left:25%;">
  <div style='background-color: #fafbfc;'>
    <div id="gist_text_field_div" style="border:1px solid #d1d5da;margin-top: 20px;">
      <div style="display:flex;margin-right:47%;">
      <input class="gist_text_field_div_input" data-editor-number="<%=(!idx.nil? ? idx.to_s : "0")%>" value="<%=((!gist_file.nil?)? gist_file.extension_type : "") %>" placeholder="Filename including extension...">
    </input>
    <button class="remove_gist_file" data-editor-number="<%=(!idx.nil? ? idx.to_s : "0")%>">
      <i class="fa fa-trash" aria-hidden="true"></i>
    </button>
  </div>
      <div style="display:flex">
        <div class="gist_text_field_item">
          <select  data-editor-number="<%=(!idx.nil? ? idx.to_s : "0")%>" id="gist_tab_size"style="
          position: relative;
          top: 50%;
          transform: translateY(-50%);
          ">
            <option value="2">Spaces</option>
            <option value="8">Tabs</option>
          </select>
        </div>
        <div class="gist_text_field_item" >
          <select  data-editor-number="<%=(!idx.nil? ? idx.to_s : "0")%>" id="gist_use_soft_tab" style="
          position: relative;
          top: 50%;
          transform: translateY(-50%);
          ">
            <option value="2">2</option>
            <option value="4">4</option>
            <option value="8">8</option>
          </select>
        </div>
        <div class="gist_text_field_item" >
          <select data-editor-number="<%=(!idx.nil? ? idx.to_s : "0")%>" id="gist_wrap_mode" >
            <option value="false">No wrap</option>
            <option value="true">Soft wrap</option>
          </select>
        </div>
      </div>
    </div>
    <div>
      <div class="gist_editor" data-extension-type="<%= (!gist_file.nil? ? gist_file.extension_type : "") %>" data-gist-file-id="<%= !gist_file.nil? ? gist_file.id : ""%>" data-editor-number="<%=(!idx.nil? ? idx.to_s : "0")%>" id="editor_<%=(!idx.nil? ? idx.to_s : "0")%>" style="width:365;height:200px;">
        <textarea style="display:none;"><%= !gist_file.nil? ? gist_file.file_content : ""%></textarea>
      </div>
    </div>
  </div>
</div>

app/views/gists/_gist_banner.html.erb
<div id="outter_banner_div">
  <div id="inner_banner_div">
    <h1>Instantly share code, notes, and snippets.</h1>
  </div>
</div>

app/views/gists/edit.html.erb
<%= render :partial => 'gist_banner'%>
<div style="width: 980px;">
  <div style="margin-left:25%;width:98%">
    <input id="gist_discription" placeholder="Gist description..."value="<%=((!@gist.nil?)? @gist.description : "") %>"></input>
  </div>
  <div class="all_gist_forms" data-gist-id="<%= @gist.id %>">
    <% @gist.gist_files.each_with_index do |gist_file,idx|  %>
      <%= render :partial => 'form', :locals => {:gist_file => gist_file,:idx => idx}  %>
    <% end %>
  </div>
  <div id="bottom_form_content">
    <div class="submit_item" style="margin-right:78%;">
      <button id="add_file">Add file</button>
    </div>
    <div id="submit_item_div">
      <div class="submit_item">
        <button id="cancel_gist" data-gist-id="<%= @gist.id %>" >Cancel</button>
      </div>
      <div class="submit_item">
        <button id="update_gist">Update</button>
      </div>
    </div>
</div>
</div>

app/views/gists/index.html.erb
<%= render :partial => 'gist_banner'%>
<div style="width: 980px;margin-left:12%">
  <div id="bottom_form_content" style="display:flex;">
    <div style="margin-left:75%;display:flex;margin-bottom:5%;">
      <div >
        <button id="new_gist">New Gist</button>
      </div>
    </div>
  </div>
  <% @all_gist.each_with_index do |gist,idx| %>
      <div style="margin-bottom: 50px;">
        <div id="show_gist_extension_type"><div style="padding:15px;color: #0366d6;"><%= link_to (!gist.gist_files.first.nil? ? gist.gist_files.first.extension_type : ""), gist_path(gist), method: :get %></div></div>
      <div>
        <div class="read_only_gist_editor" data-extension-type="<%= (!gist.gist_files.first.nil? ? gist.gist_files.first.extension_type : "") %>" data-gist-file-id="<%= !gist.gist_files.first.nil? ? gist.gist_files.first.id : ""%>" data-editor-number="<%=(!idx.nil? ? idx.to_s : "0")%>" id="editor_<%=(!idx.nil? ? idx.to_s : "0")%>">
          <textarea style="display:none;"><%= !gist.gist_files.first.nil? ? gist.gist_files.first.file_content : ""%></textarea>
        </div>
      </div>
    </div>
  <% end %>

app/views/gists/new.html.erb
  <%= render :partial => 'gist_banner'%>
  <div style="width: 980px;margin-top: 5%;">
      <div style="margin-left:25%;width:98%;">
        <input id="gist_discription" placeholder="Gist description..."></input>
      </div>
      <div class="all_gist_forms">
        <%= render :partial => 'form', :locals => {:idx => nil, :gist_file => nil}  %>
      </div>
      <div id="bottom_form_content">
        <div class="submit_item" style="margin-right:78%;">
          <button id="add_file">Add file</button>
        </div>
          <div class="submit_item">
            <button id="create_public_gist" class="create_gist">Create public gist</button>
          </div>
      </div>
    </div>

app/views/gists/show.html.erb
  <div id="outter_banner_div">
    <div id="inner_banner_div" style="display:flex;">
      <div style="margin-left:25%;"> <%= link_to 'All Gists', gists_path, method: :get %> </div>
      <div style="margin-left:35%;display:flex;">
        <%= button_to  edit_gist_path(@gist), :method => :get, class: "edit_gist" do %>
        <i class="fa fa-pencil" aria-hidden="true"></i> Edit
        <% end %>
        <%= button_to  gist_path(@gist), :method => :delete, class: "delete_gist" do %>
            <i class="fa fa-trash" aria-hidden="true"></i>Delete
        <% end %>
      </div>
    </div>
  </div>
  <br/>
  <% @gist.gist_files.each_with_index do |gist_file,idx| %>
  <div style="margin-bottom: 50px;">
    <div id="show_gist_extension_type"><div style="padding:15px;color: #0366d6;"><%= (!gist_file.nil? ? gist_file.extension_type : "") %></div></div>
    <div>
      <div class="read_only_gist_editor" data-extension-type="<%= (!gist_file.nil? ? gist_file.extension_type : "") %>" data-gist-file-id="<%= !gist_file.nil? ? gist_file.id : ""%>" data-editor-number="<%=(!idx.nil? ? idx.to_s : "0")%>" id="editor_<%=(!idx.nil? ? idx.to_s : "0")%>" >
        <textarea style="display:none;"><%= !gist_file.nil? ? gist_file.file_content : ""%></textarea>
      </div>
    </div>
  </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Github Gist Clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.9/ace.js"></script>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>